config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :social_account do
  	get 'sign_out', to: "sessions#destroy"
  end

  # get '/' => 'users#top'
  root to: 'users#top'
  delete '/blogs/:id' => 'blogs#destroy', as: 'destroy_blog'
  # delete '/clips/:id' => 'clips#destroy', as: 'destroy_clip'
  # post "blogs/comment" => "blogs#comment"

  resources :users, only: [:show, :index, :edit, :update]
  resources :blogs, only: [:new, :create, :show, :edit, :update, :index]
  resources :parties, only: [:new, :create, :show, :index]
  resources :clips, only: [:index, :destroy]
  # resources :favorites, only: [:index, :destroy]
  # resources :attend_parties, only: [:index, :destroy]
  # resource :sessions, only: [:new, :create, :destroy]

  resources :parties do
    member do
    # post "add", to: "favorites#create"
    # delete "/add", to: "favorites#destroy"
    # post "add", to: "attend_parties#create"
    # delete "/add", to: "attend_parties#destroy"
    post "add", to: "clips#create"
    # delete "/add", to: "clips#destroy"
    end
  end
  resources :blogs do
    resources :comments
  end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attend_party.rb
class AttendParty < ApplicationRecord
	belongs_to :user
	belongs_to :party
end

app/models/blog.rb
class Blog < ApplicationRecord

	belongs_to :user, optional: true
	has_many :comments, dependent: :destroy
	has_many :blog_images, dependent: :destroy
	accepts_attachments_for :blog_images, attachment: :image
	# attachment :image
end

app/models/blog_image.rb
class BlogImage < ApplicationRecord
	belongs_to :blog
	attachment :image
end

app/models/clip.rb
class Clip < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :party, optional: true
	validates :user, presence: true
	validates :party, presence: true
	validates :user_id, :uniqueness => {:scope => :party_id}
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :blog
	validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user, optional: true
	belongs_to :party, optional: true
	validates :user, presence: true
	validates :party, presence: true
end

app/models/party.rb
class Party < ApplicationRecord
	has_many :favorites
	has_many :users, through: :favorites
	has_many :attend_parties
	has_many :users, through: :attend_parties
	has_many :clips
	has_many :users, through: :clips
	belongs_to :user, optional: true

	default_scope -> { order(created_at: :desc) }

	def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Party.where(['place LIKE ?', "%#{search}%"])
    else
      Party.all #全て表示。
    end
    end
 	# attr_protected :id
 	# scope :search_names_or, lambda { |search_word| where("date = ? or place = ?", search_word, search_word) }



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :parties, through: :favorites
  has_many :attend_parties, dependent: :destroy
  has_many :parties, through: :attend_parties
  has_many :clips, dependent: :destroy
  has_many :parties, through: :clips
  attachment :image
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	# before_action :correct_user, only: [:edit, :update, :destroy]

	def new
		@blog = Blog.new
		@blog.blog_images.build
	end

	def create
		@blog = Blog.new(blog_params)
		@blog.user_id = current_user.id
		@blog.save!
		redirect_to blog_path(@blog.id)
	end

	def show
		@blog = Blog.find(params[:id])
		@comment = Comment.new
		@comments = @blog.comments
		# @comments = @blog.comments.includes(:user).all
		# @comment = @blog.comments.build(user_id: current_user.id) if curent_user
	end

	def index
		@blogs = Blog.all
		@blogs = Blog.page(params[:page]).per(10).order('created_at DESC')
		# @user = @blogs.user
		# @user = User.find_by(id: 1)
		# @blogs = Blog.where(user_id: @user.id).all
	end

	def edit
		@blog = Blog.find(params[:id])
		# unless @blogs == current_user.blogs
		# redirect_to root_path
		# end
	end

	def update
		blog = Blog.find(params[:id])
		if blog.update!(blog_params)
		flash[:success] = '更新できました！'
		redirect_to blog_path(blog.id)
		else
		render :edit
		end
	end

	def destroy
		blog = Blog.find(params[:id])
		if blog.destroy!
		flash[:success] = '削除しました'
		redirect_to root_path
		else
		render :show
		end
	end


	private
	def blog_params
		params.require(:blog).permit(:title, :body, {blog_images_images: []})
	end

	# def correct_user
	# 	blog = Blog.find(params[:id])
	# 	if current_user != user
	# 	redirect_to root_path
	# 	end
	# end


end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController

	def create
		# @user_id = current_user.user_id
		@party_id = Party.find(params[:id]).id
		if user_signed_in?
		@clip = Clip.new(party_id: @party_id, user_id: current_user.id)
		@clip.save!
			redirect_to clips_path
		else
			redirect_to root_path
		end
	end

	def destroy
		@clip = Clip.find(params[:id])
		if @clip.destroy
		   redirect_to clips_path
		end
	end

	def index
    	@user = current_user
    	@clips = @user.clips
    	# @clips = Clip.where(user_id: @user.id).all
    	# @clips = Clip.page(params[:page]).per(3).order('created_at DESC')
	end

	# def index
	# 	if user_signed_in?
	# 	# @user = current_user
	# 	@clips = Clip.where(user_id: @user.id).all
	#     else
	#     redirect_to new_user_session_path
	#     end
	# end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.build(comment_params)
		@comment.user_id = current_user.id
		if @comment.save!
			render :index
		end
	end

	def index
		@comments = Comment.all
	end

	def destroy
		@comment = Comment.find(params[:id])
		if @comment.destroy
			render :index
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:content, :blog_id, :user_id)
	end

end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
	def new
		@party = Party.new
	end

	def create
		party = Party.new(party_params)
		party.save!
		redirect_to party_path(party.id)
	end

	def show
		@party = Party.find(params[:id])
		@clips = Clip.where(party_id: @party.id).all
	end

	def index
		@parties = Party.all
		# @clips = Clip.where(party_id: @party.id).all
		@parties = Party.search(params[:search])
		@parties = Party.page(params[:page]).per(3).order('created_at DESC')
	end


	private

	def party_params
		params.require(:party).permit(:party_name, :date, :place, :attend_number, :attend_price, :belongings, :contact, :message)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def top
	end

	def index
		@users = User.all
		@users = User.page(params[:page]).per(10).order('created_at DESC')
	end

	def show
		@user = User.find(params[:id])
		@blogs = @user.blogs
		# @blogs = Blog.all
		# @blogs = Blog.where(:user_id, @user.id)
	end

	def edit
		@user = User.find(params[:id])
		# unless @user.id == current_user.id
		# redirect_to root_path
    # end
	end

	def update
		user = User.find(params[:id])
		if user.update(user_params)
		flash[:success] = '更新できました！'
		redirect_to user_path(user.id)
		else
		render :edit
		end
	end

private
    def user_params
    	params.require(:user).permit(:name, :image, :profile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attend_parties_helper.rb
module AttendPartiesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Edit your blog!</h2>


<div class="container">
  <div class="row">
    <div class="col-lg-4">
		<%= form_for(@blog) do |f| %>
  			<h4>title</h4>
  				<%= f.text_field :title %>
  			<h4>picture</h4>
  				<%= f.attachment_field :blog_images_images, multiple: true %>
  			<h4>text</h4>
  				<%= f.text_area :body %>
  			&nbsp;&nbsp;&nbsp;<p><%= f.submit "更新",class: "btn btn-warning" %></p>
 		<% end %>
 	</div>
 </div>
</div>

 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "戻る", blog_path(@blog.id), class: "btn btn-link" %>

app/views/blogs/index.html.erb

<h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Member's Blog</h2>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
		<table class="table table-striped">
  			<% @blogs.each do |blog|%>
  		<tr>
  			<td><%= attachment_image_tag blog.user, :image, :fill, 80, 80 %></td>
  			<td><%= blog.user.name %></td>
  			<td><%= blog.title %></td>
    		<td><%= link_to "詳しく", blog_path(blog.id) %></td>
  		</tr>
  			<% end %>
		</table>
	</div>
</div>
</div>

<div class="text-center"><%= paginate @blogs %></div>

<div class="text-center"><%= link_to "戻る", root_path, class: "btn btn-link" %></div>

app/views/blogs/new.html.erb

<h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Trying to spread!</h2>


<div class="container">
  <div class="row">
    <div class="col-lg-4">
<%= form_for(@blog) do |f|%>
	<h3>title</h3>
	  <%= f.text_field :title %>
	<h3>picture</h3><h5>(＊複数枚選択できます)</h5>
	  <%= f.attachment_field :blog_images_images, multiple: true %>
	<h3>text</h3>
	  <%= f.text_area :body %>&nbsp;&nbsp;&nbsp;&nbsp;<%= f.submit "投稿する",class: "btn btn-warning" %>
<% end %>
</div>
</div>
</div>


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "戻る", root_path, class: "btn btn-link" %>


app/views/blogs/show.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h3>title</h3>
        <%= @blog.title %>
      </div>
      <div class="col-lg-6">
        </br></br></br></br></br></br><%= simple_format(@blog.body) %>
        </br><% if @blog.blog_images.present? %>
              <% @blog.blog_images.each do |image| %>
              <%= attachment_image_tag image, :image, :fill, 200, 200 %>
              <% end %>
              <% else %>
                画像無し
              <% end %>

        <script type="text/javascript" src="/path/jquery-3.3.1.min.js"></script>
        <script src="js/index.js"></script>
    <div>
        &nbsp;&nbsp;&nbsp;&nbsp;<h6>コメント</h6>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments } %>
    </div>
  <% if user_signed_in? %>
    <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
  <% end %>
</div>

 <%= link_to "edit", edit_blog_path, class: "btn btn-info" %>
  <%= link_to "削除", destroy_blog_path(@blog.id), method: :delete, class: "btn btn-primary", "data-confirm" => "本当に削除しますか？" %>

    </div>
  </div>
</div>



  <div class="text-center"><%= link_to "戻る", blogs_path %></div>

app/views/clips/index.html.erb
<h4>&emsp;&emsp;&emsp;&emsp;あなたの参加予定一覧</h4>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;


<div class="container">
  <div class="row">
  	 <table class="table table-bordered">
    <!-- <div class="col-lg-8"> -->
    	<!-- <table class="table"> -->
			<% @clips.each do |clip| %>
			<% party = Party.find(clip.party_id) %>

		<tbody>
			<tr>
				<td><%= party.party_name %>さんから開催情報です</td>
				<td rowspan="8">参加者さんへ: <%= simple_format(party.message) %></td>
			</tr>
			<tr>
				<td>日付: <%= party.date %></td>
			</tr>
			<tr>
				<td>場所: <%= party.place %></td>
			</tr>
			<tr>
				<td>参加可能人数: <%= party.attend_number %>人</td>
			</tr>
			<tr>
				<td>参加費用: <%= party.attend_price %>円</td>
			</tr>
			<tr>
				<td>もちもの: <%= simple_format(party.belongings) %></td>
			</tr>
			<tr>
				<td>連絡先: <%= party.contact %></td>
			</tr>
			<tr>
				<td><%= link_to "詳細", party_path(party), class: "btn btn-info" %>
				&emsp;&emsp;&emsp;<%= link_to "参加をやめる", clip_path(clip), method: :delete, class: "btn btn-primary" %></td>
			</tr>
		</tbody>
		<% end %>
	</table>
   </div>
  </div>
</div>



<div class="text-center"><%= link_to "戻る", user_path(@user.id), class: "btn btn-link" %></div>

app/views/comments/_form.html.erb

<%= form_with(model: [blog, comment] ) do |form| %>
  <div>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit "コメントをする", class: "btn btn-default btn-ms" %>
  </div>
<% end %>

app/views/comments/_index.html.erb


<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <p><%= link_to "#{comment.user.name}さん", user_path(comment.user.id) %></p>
    <p><%= comment.content %></p>
    <div id="comments_destroy">
    <% if comment.user == current_user %>
      <p><%= link_to 'コメントを削除する', blog_comment_path(comment.blog_id, comment.id), data: { confirm: '削除する?' }, method: :delete, remote: true, class: "btn btn-link btn-xs" %></p>
    <% end %>
</div>
  <% end %>
<% end %>

app/views/comments/destroy.js.erb
// $("#flash_notice").html("<%= escape_javascript(flash[:notice])%>");
// $("#flash_notice").show(300);
$("#blog_comment_list").html("<%= escape_javascript( render(:partial => "comments/index") ) %>");
// $("#comments_destroy").html("<%= escape_javascript( render(:partial => "index") ) %>")

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.blog.comments }) %>")
$("textarea").val('')

app/views/parties/index.html.erb


<div class="container">
  <div class="row">
    <div class="col-lg-4">
    <h2> パーティー 一覧 </h2>
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<h5>場所で検索してください</h5>
        <%= form_tag parties_path, :method => 'get' do %> <%#　projects_pathはモデル名で読みかえること %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :place => nil %>
      </p>
    <% end %>
    </div>
  </div>
</div>


<!-- <table class="table table-hover"> -->
<div class="container">
  <div class="row">
    <table class="table table-bordered">
      <% @parties.each do |party| %>

      &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<tbody>
      <tr>
        <td class="info"><%= party.party_name %>さんより</td>
        <!-- <td>パーティーの詳細</td> -->
        <td rowspan="8"><%= simple_format(party.message) %></td>
      </tr>
      <tr>
	     <td>日時: <%= party.date %></td>
      </tr>
      <tr>
  	   <td>場所: <%= party.place %></td>
      </tr>
      <tr>
        <td>参加可能人数: <%= party.attend_number %>人</td>
      </tr>
      <tr>
        <td>参加費: <%= party.attend_price %>円</td>
      </tr>
      <tr>
        <td>もちもの: <%= simple_format(party.belongings) %></td>
      </tr>
      <tr>
        <td>お問い合わせ先: <%= party.contact %></td>
      </tr>
      <td><%= link_to "詳細", party_path(party.id), class: "btn btn-info" %></td>
      <% end %>
    </tbody>
    </table>
  </div>
</div>

<div class="text-center"><%= paginate @parties %></div>

<div class="text-center"><%= link_to "戻る", root_path, class: "btn btn-link" %></div>



app/views/parties/show.html.erb
<!-- <h2> パーティーの詳細です </h2> -->

<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <table class="table">
		<thead>
			<tr>
				<th><%= @party.party_name %>さんから開催情報です</th>
			</tr>
		</thead>
		<tbody>
				<tr>
					<td>日付: <%= @party.date %></td>
				</tr>
				<tr>
					<td>場所: <%= @party.place %></td>
				</tr>
				<tr>
					<td>参加人数: <%= @party.attend_number %>人</td>
				</tr>
				<tr>
					<td>現在の参加予定人数: <%= @clips.length %>人</td>
				</tr>
				<tr>
					<td>参加費: <%= @party.attend_price %>円</td>
				</tr>
				<tr>
					<td>もちもの: <%= simple_format(@party.belongings) %></td>
				</tr>
				<tr>
					<td>お問い合わせ先: <%= @party.contact %></td>
				</tr>
				<tr>
					<td><%= link_to "参加する", add_party_path(@party), method: :post, class: "btn btn-info btn-lg" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "戻る", parties_path, class: "btn btn-link btn-lg" %></td>
				</tr>


			</tbody>
		</table>
	</div>
	<div class="col-lg-6">
		<table class="table table-bordered">
			<thead>
				<p>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<th rowspan="6"><%= simple_format(@party.message) %></th>
				</p>
			</thead>
		</table>
	</div>

	



app/views/users/show.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @user.name %>さんのページ</h2>
<div class="container">
<div class="row">
  <div class="col-sm-6">
    <%= attachment_image_tag @user, :image, :fill, 130, 130 %>
  </div>
  <div class="col-sm-6">
    <%= simple_format(@user.profile) %>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "編集",edit_user_path(@user.id),class: "btn btn-link" %>
  </div>
</div>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<div class="container">
  <div class="row">
    <div class="col-lg-5">
      <table class="table">
        <h4>投稿一覧</h4>
        <tr>
            <% @blogs.each do |blog| %>
              <td><%= blog.title %></td>
              <td><%= link_to "詳しく", blog_path(blog.id) %></td>
            </tr>
            <% end %>
          </table>
          </div>
        </div>
      </div>


<div class="text-center"><%= link_to "参加予定一覧",clips_path, class: "btn btn-info" %></div>

<div class="text-center"><%= link_to "戻る", root_path, class: "btn btn-link" %></div>

app/views/users/top.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>


<body>

<div class="swiper-container">
  <div class="swiper-wrapper">
    <div class="swiper-slide"><img src="https://cdn.pixabay.com/photo/2017/03/27/13/54/bread-2178874_640.jpg"></div>
    <div class="swiper-slide"><img src="https://cdn.pixabay.com/photo/2014/06/11/17/00/cook-366875_640.jpg"></div>
    <div class="swiper-slide"><img src="https://cdn.pixabay.com/photo/2017/01/26/02/06/platter-2009590_640.jpg"></div>
  </div>
</div>


<div class="body-text">
  <u><h4>Principle</h4></u>
    <p>日本では、年間1,700万とトンの食糧廃棄物が出されています。</br>
    これは、日本におけるお米の年間収穫量に匹敵し、世界中で木々に苦しむ人々に向けた</br>
    食糧援助量を大きく上回る量です。</br>
    また、食べられるにも関わらず捨てられてしまう食品ロスが年間800万トンもあります。</br>
    そして、その半分が家庭からなのです。</br>
    こういった食品ロスは、環境への負担にもなります。</br>
    「三人寄れば文殊の知恵」。</br>
    1人では飽きたり苦痛に思ったり限界があります。友人や家族と楽しみながらやることが大事です。</br>    みなさんの家庭に、使いきれず余ってしまった食材を持ち寄って、楽しく食品ロスを解決していきましょう！
    </p>
</div>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<div class="center-block">

<div class="row">
<!-- <div class="row"> -->
  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <img src="http://hankodeasobu.com/wp-content/uploads/kitchenware_01.png"></br>
      <div class="caption1">
        <h3><%= link_to "gather people", new_party_path %></h3>
      </div>
    </div>
  </div>
<!-- </div> -->

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <img src="http://hankodeasobu.com/wp-content/uploads/party_01.png"></br></br>
      <img src="http://hankodeasobu.com/wp-content/uploads/sweets.png">
      <div class="caption2">
        <h3><%= link_to "party", parties_path %></h3>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <img src="http://hankodeasobu.com/wp-content/uploads/stationery_02.png">
      <div class="caption3">
        <h3><%= link_to "blog", new_blog_path %></h3>
      </div>
    </div>
  </div>

    <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <img src="http://hankodeasobu.com/wp-content/uploads/stationery_01.png">
      <div class="caption4">
        <h3><%= link_to "blog all", blogs_path %></h3>
      </div>
    </div>
  </div>

</div>
</div>

<div class="tsunagu-image">
  <div class="swiper-container1">
    <div class="swiper-wrapper">
      <div class="swiper-slide1"><img src="https://media.image.infoseek.co.jp/isnews/photos/walkerplus/walkerplus_59433_0.jpg"width="200" height="200"></div>
      <div class="swiper-slide1"><img src="https://cheko-blog.com/wp-content/uploads/2017/02/P2131188_.jpg" width="200" height="200"></div>
      <div class="swiper-slide1"><img src="https://kinarino.k-img.com/system/press_images/001/210/311/85a68eb69f5381878fe2cb69920c73b83ea54510.jpg?1523459683" width="200" height="200"></div>
      <div class="swiper-slide1"><img src="https://img.cpcdn.com/user_kondate_infos/74695/590x500/d8413f4fc289d5d014ddf6e9d509df54.jpg?u=9834336&p=1423829273" width="200" height="200"></div>
      <div class="swiper-slide1"><img src="https://cdn-ak.f.st-hatena.com/images/fotolife/t/tomoko_suegami/20170523/20170523163956.jpg" width="200" height="200"></div>
      <div class="swiper-slide1"><img src="https://blog-001.west.edge.storage-yahoo.jp/res/blog-1a-92/monsuke02jp/folder/200672/74/48454574/img_0?1418991107" width="200" height="200"></div>
    </div>
  </div>
</div>



<footer class="footer">
                   <div class="container">
                          <div class="text-center">
                              <ul class="list-inline small">
                                  <li>お問い合わせ</li>
                                  <li>メッセージ</li>
                              </ul>
                              <div class="my-5">
                                  <h3>Tsunagu</h3>
                                  <div class="small">Copyright © 2018 Tsunagu All Rights Reserved"</div>
                              </div>
                          </div>
                   </div>
</footer>

</body>